[package]
name = "infrapass"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1"
sui_sdk = { git = "https://github.com/mystenlabs/sui", package = "sui-sdk"}
sui-keys = { git = "https://github.com/MystenLabs/sui", package = "sui-keys" }
sui-types = { git = "https://github.com/MystenLabs/sui", package = "sui-types" }
sui-config = { git = "https://github.com/MystenLabs/sui", package = "sui-config" }
sui_json_rpc_types = { git = "https://github.com/MystenLabs/sui", package = "sui-json-rpc-types" }
sui_transaction_builder = { git = "https://github.com/MystenLabs/sui", package = "sui-transaction-builder" }
shared-crypto = { git = "https://github.com/MystenLabs/sui", package = "shared-crypto" }
tokio = { version = "1.2", features = ["full"] }
anyhow = "1.0"
serde = "1.0.118"
serde_json = "1.0.61"
