[package]
name = "infrapass"
edition = "2024"         # edition = "legacy" to use legacy (pre-2024) Move
license = "MIT"
# authors = ["..."]      # e.g., ["Joe Smith (joesmith@noemail.com)", "John Snow (johnsnow@noemail.com)"]

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
infrapass = "0x0"
